### ISSUE TITLE
ROS2 version?

### ISSUE THREAD

**Issue by clydemcqueen** [daniilidis-group/ffmpeg_image_transport#1]
Hello! Is there a ROS2 version planned? Thanks.

**Comment by berndpfrommer** [comment]
Sorry, not in the near future. I have started to use ROS2 but I am not using the ffmpeg image transport for any of my current projects.

**Comment by berndpfrommer** [comment]
First cut is ready, I will be testing over the next few weeks.
https://github.com/berndpfrommer/ffmpeg_image_transport
