### ISSUE TITLE
Decode the ffmpeg image

### ISSUE THREAD

**Issue by alrousanqusay** [daniilidis-group/ffmpeg_image_transport#4]
Am transmitting the ffmpeg image to a remote computer, Is there a way to decode the ffmpeg image after transmitting the image over UDP

When i try to this i got the following warning
![image](https://user-images.githubusercontent.com/64987434/134987363-b609065e-d92b-43bf-a044-3c9a996da1cd.png)

**Comment by berndpfrommer** [comment]
Is this related to #3?
