### ISSUE TITLE
License for use

### ISSUE THREAD

**Issue by SJamieson** [daniilidis-group/ffmpeg_image_transport#9]
My lab group and I are very interested in using this for streaming video in our underwater robotics project but noticed that there is no license posted -- would you consider releasing the code under either a permissive license or a license permitting academic and/or non-commercial use?

Thank you very much for creating this!

**Comment by SJamieson** [comment]
Oh and https://github.com/daniilidis-group/ffmpeg_image_transport_msgs would need to be updated with a license that is at least as permissive

**Comment by berndpfrommer** [comment]
added apache-2 license, enjoy.
